name: Update Dev Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm cache clean --force
    - run: npm install
    - run: npm run build

    - name: Create or Update Dev Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: dev
        name: Development Build
        body: This is the latest development build of the plugin.
        draft: false
        prerelease: true
        files: |
          main.js
          manifest.json
          styles.css