name: Update Dev Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npm ci
    - run: npm run build

    - name: Debug - List files
      run: |
        echo "Root directory contents:"
        ls -la
        echo "src directory contents:"
        ls -la src || echo "src directory not found"

    - name: Create Release Files
      run: |
        mkdir release
        cp main.js manifest.json styles.css release/
        echo "Release directory contents:"
        ls -la release

    - name: Create release.zip
      run: zip -r release.zip main.js manifest.json styles.css

    - name: Debug - Check file existence
      run: |
        echo "Checking for main.js:"
        ls -l main.js || echo "main.js not found in root"
        echo "Checking for release/main.js:"
        ls -l release/main.js || echo "main.js not found in release folder"
        echo "Checking for release.zip:"
        ls -l release.zip || echo "release.zip not found"

    - name: Create or Update Dev Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: dev
        name: Development Build
        body: This is the latest development build of the plugin.
        draft: false
        prerelease: true
        files: |
          release.zip
          main.js
          manifest.json
          styles.css

    # Remove the Upload Build Folder step as it's no longer needed
